object BuildDependenciesVersions {
    const val KOTLIN = "1.4.10"
    const val APPCOMPAT = "1.2.0"
    const val MATERIAL = "1.2.1"
    const val COROUTINES = "1.3.9"
    const val ROOM = "2.2.5"
    const val NAVIGATION = "2.3.0"
    const val LIFECYCLE = "2.2.0"
    const val CORE_KTX = "1.3.2"
    const val LOGGING = "4.9.0"
    const val FRAGMENT_KTX = "1.2.5"
    const val PAGING = "3.0.1"
    const val CONSTRAIN_LAYOUT = "2.0.2"
    const val GLIDE = "4.12.0"
    const val LEAKCANARY = "2.5"
    const val DATABINDING = "3.1.4"
    const val KOIN = "3.1.3"
    const val APOLLO = "2.5.9"
}
